function(DetectValueForParam VAR_NAME defaultvalue)
    if(DEFINED ${VAR_NAME})
        return()
    endif()
    
    set (CONFIGFILE ${CMAKE_CURRENT_LIST_DIR}/../.config)
    
    if(DEFINED ENV{${VAR_NAME}})
        set(${VAR_NAME} $ENV{${VAR_NAME}} CACHE INTERNAL "")
        return()
    endif()


    file(READ ${CONFIGFILE} DEVEL_CONFIG)
    string(REGEX REPLACE "\n" ";" DEVEL_CONFIG "${DEVEL_CONFIG}")
    foreach(kvp ${DEVEL_CONFIG})
        string(REPLACE "=" ";" kvplist ${kvp})
        list(GET kvplist 0 kvpkey)
        list(GET kvplist 1 kvpvalue)
        message(${kvp})
        if ("${kvpkey}" STREQUAL "${VAR_NAME}")
            set(${VAR_NAME} ${kvpvalue} GLOBAL_SCOPE)
            set(${VAR_NAME} ${kvpvalue} CACHE INTERNAL "")
        endif()
    endforeach()
    if(NOT DEFINED ${VAR_NAME})
        message(WARNING "Cannot find ${VAR_NAME} in ${CONFIGFILE}")
        file(APPEND ${CONFIGFILE} "${VAR_NAME}=${defaultvalue}\n")
        DetectValueForParam(${VAR_NAME} ${defaultvalue})
    endif()
endfunction()

function(DetectPath name defaultvalue)
    DetectValueForParam(${name} ${defaultvalue})
 endfunction()